<a href="https://colab.research.google.com/github/kul-pat/Public-Machine-learning/blob/main/KNN_algorithms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score
from sklearn.preprocessing import StandardScaler


In [ ]:
df = pd.read_csv('data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [ ]:
df.dropna(axis=1,inplace=True)
df

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302         M  ...          0.4601                  0.11890
1      842517         M  ...          0.2750                  0.08902
2    84300903         M  ...          0.3613                  0.08758
3    84348301         M  ...          0.6638                  0.17300
4    84358402         M  ...          0.2364                  0.07678
..        ...       ...  ...             ...                      ...
564    926424         M  ...          0.2060                  0.07115
565    926682         M  ...          0.2572                  0.06637
566    926954         M  ...          0.2218                  0.07820
567    927241         M  ...          0.4087                  0.12400
568     92751         B  ...          0.2871                  0.07039

[569 rows x 32 columns]

In [ ]:
df.set_index('id',inplace=True)
df

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
id                               ...                                         
842302           M        17.99  ...          0.4601                  0.11890
842517           M        20.57  ...          0.2750                  0.08902
84300903         M        19.69  ...          0.3613                  0.08758
84348301         M        11.42  ...          0.6638                  0.17300
84358402         M        20.29  ...          0.2364                  0.07678
...            ...          ...  ...             ...                      ...
926424           M        21.56  ...          0.2060                  0.07115
926682           M        20.13  ...          0.2572                  0.06637
926954           M        16.60  ...          0.2218                  0.07820
927241           M        20.60  ...          0.4087                  0.12400
92751            B         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [ ]:
df.shape

(569, 31)

In [ ]:
df.loc[842302]

diagnosis                         M
radius_mean                   17.99
texture_mean                  10.38
perimeter_mean                122.8
area_mean                      1001
smoothness_mean              0.1184
compactness_mean             0.2776
concavity_mean               0.3001
concave points_mean          0.1471
symmetry_mean                0.2419
fractal_dimension_mean      0.07871
radius_se                     1.095
texture_se                   0.9053
perimeter_se                  8.589
area_se                       153.4
smoothness_se              0.006399
compactness_se              0.04904
concavity_se                0.05373
concave points_se           0.01587
symmetry_se                 0.03003
fractal_dimension_se       0.006193
radius_worst                  25.38
texture_worst                 17.33
perimeter_worst               184.6
area_worst                     2019
smoothness_worst             0.1622
compactness_worst            0.6656
concavity_worst             

In [ ]:
# encoding the categorical data values
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
df.iloc[:,0] = labelencoder_y.fit_transform(df.iloc[:,0].values)
df.iloc[:,0]

id
842302      1
842517      1
84300903    1
84348301    1
84358402    1
           ..
926424      1
926682      1
926954      1
927241      1
92751       0
Name: diagnosis, Length: 569, dtype: int64

In [ ]:
# split dataset
X =df.drop('diagnosis',axis =1)
y =df['diagnosis']
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
X

radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
id                                   ...                                         
842302          17.99         10.38  ...          0.4601                  0.11890
842517          20.57         17.77  ...          0.2750                  0.08902
84300903        19.69         21.25  ...          0.3613                  0.08758
84348301        11.42         20.38  ...          0.6638                  0.17300
84358402        20.29         14.34  ...          0.2364                  0.07678
...               ...           ...  ...             ...                      ...
926424          21.56         22.39  ...          0.2060                  0.07115
926682          20.13         28.25  ...          0.2572                  0.06637
926954          16.60         28.08  ...          0.2218                  0.07820
927241          20.60         29.33  ...          0.4087                  0.12400
92751            7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [ ]:
y

id
842302      1
842517      1
84300903    1
84348301    1
84358402    1
           ..
926424      1
926682      1
926954      1
927241      1
92751       0
Name: diagnosis, Length: 569, dtype: int64

In [ ]:
# scale the data (" feature sclaing")
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
X_train

array([[-1.15036482, -0.39064196, -1.12855021, ..., -0.75798367,
        -0.01614761, -0.38503402],
       [-0.93798972,  0.68051405, -0.94820146, ..., -0.60687023,
         0.09669004, -0.38615797],
       [ 0.574121  , -1.03333557,  0.51394098, ..., -0.02371948,
        -0.20050207, -0.75144254],
       ...,
       [-1.32422924, -0.20048168, -1.31754581, ..., -0.97974953,
        -0.71542314, -0.11978123],
       [-1.24380987, -0.2245526 , -1.28007609, ..., -1.75401433,
        -1.58157125, -1.00601779],
       [-0.73694129,  1.14989702, -0.71226578, ..., -0.27460457,
        -1.25895095,  0.21515662]])

In [ ]:
import math
math.sqrt(len(y_test))

10.677078252031311

In [ ]:
# Define the model : KNN
classifier =KNeighborsClassifier(algorithm='auto',weights='uniform',leaf_size=1,p=1,metric='manhattan',n_neighbors=11)

In [ ]:
#fit_model
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=1, metric='manhattan',
                     metric_params=None, n_jobs=None, n_neighbors=11, p=1,
                     weights='uniform')

In [ ]:
# predict the test set results
y_pred = classifier.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0])

In [ ]:
# evluate the model
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[66  1]
 [ 4 43]]


In [ ]:
print(f1_score(y_test,y_pred))

0.945054945054945


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.99      0.96        67
           1       0.98      0.91      0.95        47

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [ ]:
##Randomized Search Cv
from sklearn.model_selection import GridSearchCV
p=[1,2]
weights=['uniform','distance']
algorithm =['auto','ball_tree','kd_tree','brute']
metric = ['euclidean','manhattan','minkowski']
# Create the random grid
random_grid = {'n_neighbors':np.arange(1,50),
               'leaf_size':np.arange(1,20),
               'p': p,'weights': weights,'algorithm':algorithm,
               'metric': metric
            }
print(random_grid)

{'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]), 'leaf_size': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19]), 'p': [1, 2], 'weights': ['uniform', 'distance'], 'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'], 'metric': ['euclidean', 'manhattan', 'minkowski']}


In [ ]:
# using the RandomizesearchCV 
knn_2 = KNeighborsClassifier()
clf =GridSearchCV(knn_2,random_grid,cv=5,scoring='accuracy')
clf.fit(X_train,y_train)

KeyboardInterrupt: ignored

In [ ]:
clf.best_params_

{'algorithm': 'auto',
 'leaf_size': 1,
 'metric': 'manhattan',
 'n_neighbors': 11,
 'p': 1,
 'weights': 'uniform'}

In [ ]:
clf.best_score_

0.9692307692307693